### ISSUE TITLE
laravel-pdflayer limitations?

### ISSUE THREAD

**Issue by MatiasManevi** [mathieutu/laravel-pdflayer#2]
I am doing an app in Laravel and I found many problems to render HTML to PDF with laravel-dompdf, until I found pdflayer, which is very useful for me but its free plan only allows 100 requests /per month.

This repository, how does it relate to pdflayer?
Do you have any kind of limit for conversions?

**Comment by mathieutu** [comment]
Hi,

The http://pdflayer.com platform is an HTML to PDF conversion API for developers. 
This package is an unofficial bridge, which let you use this api in a elegant way with the PHP Laravel framework.

All the limitations, and specificities about http://pdflayer.com are theirs, and I'm not responsible about that. Under the hood this package just call the pdflayer API, and depends on it.

Does this answer help you understand?

**Comment by MatiasManevi** [comment]
Yes, thank you mathieu
